### ISSUE TITLE
Patient ID is displayed in the Patients listing

### ISSUE THREAD

**Issue by mmuller** [instedd/maap-collector#109] opened 2019-08-23 12:52 UTC
Steps to reproduce:
Add a Patient `P` from the Collector.
Go to the Store.
Navigate to the Patients listing.
Observe the Patient ID for the Patient `P`. 

Obtained:
The Patient ID is shown in the Patients listing.

![image](https://user-images.githubusercontent.com/518152/63593842-3f061500-c58b-11e9-99ee-6ae0f9eea91a.png)

**Comment by hdf1986** [comment] 2019-08-23 19:25
Closing since this is by design, currently the patient id remains just a few moments until `ObfuscatePatientIdsWorker` runs an executes their job obfuscating.

This is like this since there are some concurrence issues if you instead create the obfuscated patient ids on the fly in the api endpoints, instead the aproach is to save the patient id as is and run a cron job worker to obfuscate the fields

**Closed by hdf1986** 2019-08-23 19:25 UTC
Labels: bug
